name: matrix_calculate
description: Matrix Calculator
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  badges: ^3.1.1
  bloc: ^8.1.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  http: ^1.0.0
  intl: ^0.18.0
  matrix:
    git:
      url: https://github.com/NonymousMorlock/matrix.git
  provider: ^6.0.5
  responsive_framework: ^1.0.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
